title: configureV1
basic_behavior:
  verbose : true
  time_interval: 10
  dump_all : false
#unit in Mb/s
global_limit_Mbit_per_sec: 1000
basic_limit:
  Host_Mbit_per_sec:   
    202.129.205.94 :  50
    74.125.213.240 : 100
  tcp_port_limit_Mbit_per_sec:
    80: 10
    53: 10
    8080: 5