title: configureV1
basic_behavior:
  verbose : false
  time_interval: 10
  num_rules : 5
#unit in Mb/s
global_limit: 1000
basic_limit:   
  74.125.213.210 : 100
  158.108.210.123 : 20
  202.129.205.94 :  10